#!/usr/bin/env node
/**
 * compile-schemas.mjs — MIR 2.2 Schema Compiler.
 *
 * Pre-compiles mir_gamestate.schema.json + mir_types.schema.json into a
 * standalone ESM validation function with zero runtime dependencies.
 *
 * The output file (src/state/validation/compiledValidate.mjs) works in both
 * Node and browser without Ajv at runtime.
 *
 * Usage: node scripts/compile-schemas.mjs
 * Run whenever schemas change.
 */

import Ajv from "ajv";
import addFormats from "ajv-formats";
import standaloneCode from "ajv/dist/standalone/index.js";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const OUT = resolve(ROOT, "src/state/validation/compiledValidate.mjs");

// Load schemas
const typesSchema = JSON.parse(
  readFileSync(resolve(ROOT, "schemas/mir_types.schema.json"), "utf-8")
);
const gameStateSchema = JSON.parse(
  readFileSync(resolve(ROOT, "schemas/mir_gamestate.schema.json"), "utf-8")
);

// Compile with standalone ESM output
const ajv = new Ajv({
  allErrors: true,
  strict: false,
  validateSchema: false,
  code: { source: true, esm: true },
});
addFormats(ajv);
ajv.addSchema(typesSchema, "mir_types.schema.json");
const validate = ajv.compile(gameStateSchema);

let code = standaloneCode(ajv, validate);

// ── Post-process: replace CJS require() calls with inline ESM equivalents ──
// The standalone generator emits require() for runtime helpers even in ESM mode.
// We inline these helpers so the output has zero external dependencies.

// 1. ucs2length — counts Unicode code points (handles surrogate pairs)
code = code.replace(
  /const func1 = require\("ajv\/dist\/runtime\/ucs2length"\)\.default;/,
  `const func1 = (s) => {
  let len = 0;
  for (let i = 0; i < s.length; i++) {
    if ((s.charCodeAt(i) & 0xfc00) === 0xd800) i++;
    len++;
  }
  return len;
};`
);

// 2. date-time format validator from ajv-formats
code = code.replace(
  /const formats0 = require\("ajv-formats\/dist\/formats"\)\.fullFormats\["date-time"\];/,
  `const formats0 = {
  validate: (s) => /^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?(?:Z|[+-]\\d{2}:\\d{2})$/.test(s) && !isNaN(Date.parse(s))
};`
);

// 3. Remove "use strict" (not needed in ESM, causes issues in some environments)
code = code.replace(/^"use strict";/, "");

// Verify no require() calls remain
if (code.includes("require(")) {
  const remaining = code.match(/require\([^)]+\)/g);
  console.error("⚠ Remaining require() calls:", remaining);
  process.exit(1);
}

// Write output
mkdirSync(dirname(OUT), { recursive: true });

const header = `/**
 * compiledValidate.mjs — AUTO-GENERATED by scripts/compile-schemas.mjs
 *
 * Standalone GameState schema validator. Zero runtime dependencies.
 * Works in both Node and browser ESM.
 *
 * DO NOT EDIT — regenerate with: node scripts/compile-schemas.mjs
 * Generated: ${new Date().toISOString()}
 */

`;

writeFileSync(OUT, header + code, "utf-8");
console.log(`✅ Compiled schema validator → ${OUT}`);
console.log(`   ${code.length} chars, zero runtime deps`);
